# Generated by Django 4.1 on 2023-06-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_bim_condition_bmi'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyBuilderGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BodyExpectantMotherGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DiabeticGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
    ]
